# Generated by Django 2.1.2 on 2018-10-23 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdopcionMascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Adoptador',
            fields=[
                ('NombreUsuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ApellidoPaterno', models.CharField(max_length=15)),
                ('ApellidoMaterno', models.CharField(max_length=15)),
                ('NombreCompleto', models.CharField(max_length=30)),
                ('Correo', models.EmailField(max_length=50)),
                ('Contraseña', models.CharField(max_length=15)),
                ('ConfirmarContraseña', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('Imagen', models.ImageField(upload_to='templates/adopcionperros/perrisimagenes/')),
                ('NombreMascota', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('RazaPredominante', models.CharField(max_length=15)),
                ('Descripcion', models.TextField()),
                ('Estado', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='adopcionmascota',
            name='Adoptador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcionperros.Adoptador'),
        ),
        migrations.AddField(
            model_name='adopcionmascota',
            name='Mascotas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcionperros.Mascotas'),
        ),
    ]
