# Generated by Django 2.1.2 on 2018-10-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcionperros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascotas',
            name='ESTADO',
        ),
        migrations.AddField(
            model_name='mascotas',
            name='Estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Rescatado', 'Rescatado'), ('Adoptado', 'Adoptado')], default='Disponible', max_length=10),
        ),
    ]
