# Generated by Django 2.1.2 on 2018-10-24 00:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adopcionperros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptador',
            name='FechaRegistro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='FechaPublicado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
