# Generated by Django 2.1.2 on 2018-10-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcionperros', '0002_auto_20181023_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='Imagen',
            field=models.ImageField(upload_to='static/uploadimages'),
        ),
    ]
