# Generated by Django 2.1.2 on 2018-10-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcionperros', '0002_auto_20181029_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptarMascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adoptador', models.CharField(max_length=45)),
                ('MascotaAdoptada', models.CharField(max_length=20)),
                ('FechaAdoptado', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
