# Generated by Django 2.1.2 on 2018-10-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcionperros', '0003_adoptarmascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptarmascota',
            name='FechaAdoptado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
