# Generated by Django 2.1.2 on 2018-10-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcionperros', '0003_auto_20181023_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascotas',
            name='Estado',
        ),
        migrations.AddField(
            model_name='mascotas',
            name='ESTADO',
            field=models.CharField(choices=[('R', 'Rescatado'), ('D', 'Disponible'), ('A', 'Adoptado')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='Imagen',
            field=models.ImageField(upload_to='upload'),
        ),
    ]
