# Generated by Django 2.1.2 on 2018-10-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcionperros', '0004_auto_20181023_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='Imagen',
            field=models.ImageField(upload_to='adopcionperros/static/upload'),
        ),
    ]
