# Generated by Django 2.1.2 on 2018-10-31 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcionperros', '0004_auto_20181030_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptarmascota',
            name='FechaAdoptado',
        ),
    ]
