# Generated by Django 2.1.2 on 2018-10-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcionperros', '0005_auto_20181023_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='Imagen',
            field=models.ImageField(upload_to='upload'),
        ),
    ]
