# Generated by Django 2.1.2 on 2018-10-25 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcionperros', '0006_auto_20181024_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptador',
            old_name='Correo',
            new_name='CorreoElectronico',
        ),
        migrations.RemoveField(
            model_name='adoptador',
            name='FechaRegistro',
        ),
    ]
