# Generated by Django 2.1.2 on 2018-10-25 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcionperros', '0007_auto_20181024_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptador',
            old_name='NombreCompleto',
            new_name='Nombres',
        ),
        migrations.RemoveField(
            model_name='adoptador',
            name='ApellidoMaterno',
        ),
    ]
