# Generated by Django 2.1.2 on 2018-10-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcionperros', '0008_auto_20181024_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptador',
            name='Nombres',
            field=models.CharField(max_length=20),
        ),
    ]
